---
title: 'WBE of COVID19'
author: "Emily Riseberg"
date: "Created 11/23/2021"
output: pdf_document
---
  
```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(mgcv)
library(DescTools)
library(MASS)
library(foreign)
library(cowplot)
library(lubridate)
library(weathermetrics)

```

## Load data
```{r}
load("/Users/emilyriseberg/Desktop/NEIWPCC/MWRAMA_LagDat_LONG.RData")
load("/Users/emilyriseberg/Desktop/NEIWPCC/PortlandData.RData")
# load("/Users/emilyriseberg/Desktop/NEIWPCC/YaleData.RData")

## Can't do log with 0
port <- port[which(!is.na(port$copies.1mL)),]
port_ln <- port

port_ln <- port_ln[which(port_ln$Incidence.in.town != 0),]
port_ln <- port_ln[which(port_ln$copies.1mL != 0),]

## Divide by 7
port_ln[,"IncRateORIG"]<-port_ln[,"IncRate"]
port_ln[,"IncORIG"]<-port_ln[,"Incidence.in.town"]

for (i in 1:nrow(port_ln))
{
  port_ln[i,"IncRate"] <- (port_ln[i,"Incidence.in.town"]/7)/port_ln[i,"Population"]
  port_ln[i,"Incidence.in.town"]<-port_ln[i,"Incidence.in.town"]/7
}
port_ln[,"Incidence.in.town"]<-round(port_ln[,"Incidence.in.town"], digits=0)

## Convert temp to celsius
unadj_time$TAVG<-fahrenheit.to.celsius(unadj_time$TAVG)
adj_4day$TAVG<-fahrenheit.to.celsius(adj_4day$TAVG)
adj_5day$TAVG<-fahrenheit.to.celsius(adj_5day$TAVG)
adj_6day$TAVG<-fahrenheit.to.celsius(adj_6day$TAVG)

port_ln$TAVG<-fahrenheit.to.celsius(port_ln$TAVG)
#yale$TAVG<-fahrenheit.to.celsius(yale$TAVG)

## Look at correlation (going in results section)
cor.test(unadj_time[which(unadj_time$Facility=="North"),"TAVG"],
         unadj_time[which(unadj_time$Facility=="North"),"copies.1mL"], method="spearman")
cor.test(unadj_time[which(unadj_time$Facility=="South"),"TAVG"],
         unadj_time[which(unadj_time$Facility=="South"),"copies.1mL"], method="spearman")

cor.test(port_ln[which(port_ln$Name=="EE"),"TAVG"],
         port_ln[which(port_ln$Name=="EE"),"copies.1mL"], method="spearman")
cor.test(port_ln[which(port_ln$Name=="WB"),"TAVG"],
         port_ln[which(port_ln$Name=="WB"),"copies.1mL"], method="spearman")

#cor.test(yale$TAVG, yale$copies.1mL, method="spearman")
```

## ALL MODELS
## For table 2, table 3, supplemental table 2, and supplemental table 3

## Linear - unadjusted
```{r}
## MA
summary(res<-lm(log(IncRate) ~ log(copies.1mL), data=unadj_time))
confint(res)
sqrt(mean(res$residuals^2))

# ## CT
# summary(res<-lm(log(IncRate) ~ log(copies.1mL), data=yale))
# confint(res)
# sqrt(mean(res$residuals^2))

## ME
summary(res<-lm(log(IncRate) ~ log(copies.1mL), data=port_ln))
confint(res)
sqrt(mean(res$residuals^2))

## ME - Sensitivity
summary(res<-lm(log(IncRateORIG) ~ log(copies.1mL), data=port_ln))
confint(res)
sqrt(mean(res$residuals^2))
```

## Linear - adjusted
```{r}
## MA
summary(res<-lm(log(IncRate) ~ log(copies.1mL) + FlowRate_MGD + TAVG + Facility, data=unadj_time))
confint(res)
VIF(res)
sqrt(mean(res$residuals^2))
mass_fin <- data.frame(unadj_time[which(!is.na(unadj_time$copies.1mL)),],data.frame(predict(res)))
mass_fin[,"PredIncRate"]<-exp(mass_fin[,"predict.res."])

# ## CT
# summary(res<-lm(log(IncRate) ~ log(copies.1mL) + TAVG, data=yale))
# confint(res)
# VIF(res)
# sqrt(mean(res$residuals^2))
# yale_fin <- data.frame(yale[intersect(which(!is.na(yale$copies.1mL)),which(!is.na(yale$IncRate))),],
#                        data.frame(predict(res)))
# yale_fin[,"PredIncRate"]<-exp(yale_fin[,"predict.res."])

## ME
summary(res<-lm(log(IncRate) ~ log(copies.1mL) + FlowRate_MGD + TAVG + town, data=port_ln))
confint(res)
VIF(res)
sqrt(mean(res$residuals^2))
port_fin <- data.frame(port_ln[which(!is.na(port_ln$copies.1mL)),],data.frame(predict(res)))
port_fin[,"PredIncRate"]<-exp(port_fin[,"predict.res."])

## ME - sensitivity
summary(res<-lm(log(IncRateORIG) ~ log(copies.1mL) + FlowRate_MGD + TAVG + town, data=port_ln))
confint(res)
sqrt(mean(res$residuals^2))

```

## GAM regression - unadjusted
```{r}
## MA
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr"), data=unadj_time))
sqrt(mean(gam$residuals^2))

# ## CT
# summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr"), data=yale))
# sqrt(mean(gam$residuals^2))

## ME
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL) , bs="cr"), data=port_ln))
sqrt(mean(gam$residuals^2))

## ME - sensitivity
summary(gam<-gam(log(IncRateORIG) ~ s(log(copies.1mL) , bs="cr"), data=port_ln))
sqrt(mean(gam$residuals^2))
```

## GAM regression - adjusted
```{r}
## MA
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr") + FlowRate_MGD + TAVG + Facility,
                 data=unadj_time))
sqrt(mean(gam$residuals^2))
mass_fin <- data.frame(mass_fin,data.frame(predict(gam)))
mass_fin[,"PredIncRate_GAM"]<-exp(mass_fin[,"predict.gam."])

# ## CT
# summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr") + TAVG, data=yale))
# sqrt(mean(gam$residuals^2))
# yale_fin <- data.frame(yale_fin,data.frame(predict(gam)))
# yale_fin[,"PredIncRate_GAM"]<-exp(yale_fin[,"predict.gam."])

## ME
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr") + FlowRate_MGD + TAVG + town, 
                 data=port_ln))
sqrt(mean(gam$residuals^2))
port_fin <- data.frame(port_fin,data.frame(predict(gam)))
port_fin[,"PredIncRate_GAM"]<-exp(port_fin[,"predict.gam."])

## ME - sensitivity
summary(gam<-gam(log(IncRateORIG) ~ s(log(copies.1mL), bs="cr") + FlowRate_MGD + TAVG + town, 
                 data=port_ln))
sqrt(mean(gam$residuals^2))
```


## Poisson regression - unadjusted
```{r}
## MA
summary(poisson <- glm(round(unadj_time$NewCases, digits=0) ~ log(copies.1mL), 
                       family="poisson", data=unadj_time))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))

# ## CT
# summary(poisson <- glm(NumPosTests_ByDateReport ~ log(copies.1mL), family="poisson", data=yale))
# confint(poisson)
# PseudoR2(poisson, which = 'McFadden')
# sqrt(mean(poisson$residuals^2))

## ME
summary(poisson <- glm(Incidence.in.town ~ log(copies.1mL), family="poisson", data=port_ln))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))

## ME - sensitivity
summary(poisson <- glm(IncORIG ~ log(copies.1mL), family="poisson", data=port_ln))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
```

## Poisson regression - adjusted
```{r}
## MA
summary(poisson <- glm(round(unadj_time$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, family="poisson", data=unadj_time))
confint(poisson)
VIF(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
mass_fin <- data.frame(mass_fin,data.frame(predict(poisson)))

# ## CT
# summary(poisson <- glm(NumPosTests_ByDateReport ~ log(copies.1mL) + 
#                          TAVG, family="poisson", data=yale))
# confint(poisson)
# VIF(poisson)
# PseudoR2(poisson, which = 'McFadden')
# sqrt(mean(poisson$residuals^2))
# yale_fin <- data.frame(yale_fin,data.frame(predict(poisson)))

## ME
summary(poisson <- glm(Incidence.in.town ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + town, family="poisson", data=port_ln))
confint(poisson)
VIF(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
port_fin <- data.frame(port_fin,data.frame(predict(poisson)))

## ME - sensitivity
summary(poisson <- glm(IncORIG ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + town, family="poisson", data=port_ln))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
port_fin <- data.frame(port_fin,data.frame(predict(poisson)))
```

## Negative binomial regression - unadjusted
```{r}
## MA
summary(negbin <- glm.nb(round(unadj_time$NewCases, digits=0) ~ log(copies.1mL), data=unadj_time))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
# 
# ## CT
# summary(negbin <- glm.nb(NumPosTests_ByDateReport ~ log(copies.1mL), data=yale))
# confint(negbin)
# PseudoR2(negbin, which = 'McFadden')
# sqrt(mean(negbin$residuals^2))

## ME
summary(negbin <- glm.nb(Incidence.in.town ~ log(copies.1mL), data=port_ln))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))

## ME - sensitivity
summary(negbin <- glm.nb(IncORIG ~ log(copies.1mL), data=port_ln))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
```

## Negative binomial regression - adjusted
```{r}
## MA
summary(negbin <- glm.nb(round(unadj_time$NewCases, digits=0) ~ log(copies.1mL) + 
                           FlowRate_MGD + TAVG + Facility, data=unadj_time))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
mass_fin <- data.frame(mass_fin,data.frame(predict(negbin)))

# ## CT
# summary(negbin <- glm.nb(NumPosTests_ByDateReport ~ log(copies.1mL)  + 
#                            TAVG , data=yale))
# confint(negbin)
# PseudoR2(negbin, which = 'McFadden')
# sqrt(mean(negbin$residuals^2))
# yale_fin <- data.frame(yale_fin,data.frame(predict(negbin)))

## ME
summary(negbin <- glm.nb(Incidence.in.town ~ log(copies.1mL) + 
                           FlowRate_MGD + TAVG + town, data=port_ln))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
port_fin <- data.frame(port_fin,data.frame(predict(negbin)))

## ME - sensitivity
summary(negbin <- glm.nb(IncORIG ~ log(copies.1mL) + 
                           FlowRate_MGD + TAVG + town, data=port_ln))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
port_fin <- data.frame(port_fin,data.frame(predict(negbin)))
```

## Table 1
```{r}
## TO GO IN RESULTS (from 2019 census, used to calculate std. incidence):
## Westbrook and Gorham total population: 37052
## Portland population: 66215
## North MWRA: 1605054
## South MWRA: 781829
## New Haven: 130250

## Set-up -- not in results
north <- unadj_time[which(unadj_time$Facility=="North"),]
south <- unadj_time[which(unadj_time$Facility=="South"),]
north$Date==south$Date
## Yes

allmass <- data.frame(Date_north=north$Date,
                      Date_south=south$Date,
                      Inc_north=north$NewCases,
                      Inc_south=south$NewCases,
                      TAVG_north=north$TAVG,
                      TAVG_south=south$TAVG,
                      Flow_north=north$FlowRate_MGD,
                      Flow_south=south$FlowRate_MGD,
                      Copies_north=north$copies.1mL,
                      Copies_south=south$copies.1mL,
                      IncRate_north=north$IncRate,
                      IncRate_south=south$IncRate)
allmass$TAVG_north==allmass$TAVG_south
## same
allmass$TAVG<-allmass$TAVG_north
ratio_north_all <- 1605054/(1605054+781829)
ratio_south_all <- 781829/(1605054+781829)

allmass$copies.1mL<-(ratio_north_all*allmass$Copies_north)+
  (ratio_south_all*allmass$Copies_south)
allmass$FlowRate_MGD<-(ratio_north_all*allmass$Flow_north)+
  (ratio_south_all*allmass$Flow_south)
allmass$NewCases<-(allmass$Inc_north+allmass$Inc_south)
allmass$IncRate<-allmass$NewCases/(1605054+781829)


allport <- data.frame(Date_EE=port_EE$Date,
                      Date_WB=port_WB$Date,
                      Inc_EE=port_EE$Incidence.in.town,
                      Inc_WB=port_WB$Incidence.in.town,
                      TAVG_EE=port_EE$TAVG,
                      TAVG_WB=port_WB$TAVG,
                      Flow_EE=port_EE$FlowRate_MGD,
                      Flow_WB=port_WB$FlowRate_MGD,
                      Copies_EE=port_EE$copies.1mL,
                      Copies_WB=port_WB$copies.1mL,
                      IncRate_EE=port_EE$IncRate,
                      IncRate_WB=port_WB$IncRate)
allport$Date_EE==allport$Date_WB
## one week not same, still same week


ratio_EE_all<-66215/(66215+37052)
ratio_WB_all<-37052/(66215+37052)
allport$copies.1mL<-(ratio_EE_all*allport$Copies_EE)+
  (ratio_WB_all*allport$Copies_WB)
allport$TAVG<-(ratio_EE_all*allport$TAVG_EE)+
  (ratio_WB_all*allport$TAVG_WB)
allport$FlowRate_MGD<-(ratio_EE_all*allport$Flow_EE)+
  (ratio_WB_all*allport$Flow_WB)
allport$Incidence.in.town<-(allport$Inc_EE+allport$Inc_WB)/7
allport$IncRate<-allport$Incidence.in.town/(66215+37052)

allport$TAVG <- fahrenheit.to.celsius(allport$TAVG)

## In results:

## Copies
summary(allmass$copies.1mL)
# summary(yale$copies.1mL)
summary(allport$copies.1mL)

## Cases
summary(allmass$NewCases)
# summary(yale$NumPosTests_ByDateReport)
summary(allport$Incidence.in.town)

## Inc rate
summary(allmass$IncRate*10000)
# summary(yale$IncRate*10000)
summary(allport$IncRate*10000)

## Temp
summary(allmass$TAVG)
# summary(yale$TAVG)
summary(allport$TAVG)

## Flow
summary(allmass$FlowRate_MGD)
summary(allport$FlowRate_MGD)

```

## Supplemental table 2
```{r}
## Set-up
port_EE <- port_EE[which(!is.na(port_EE$copies.1mL)),]
port_EE <- port_EE[which(port_EE$Incidence.in.town != 0),]
port_EE <- port_EE[which(port_EE$copies.1mL != 0),]

port_WB <- port_WB[which(!is.na(port_WB$copies.1mL)),]
port_WB <- port_WB[which(port_WB$Incidence.in.town != 0),]
port_WB <- port_WB[which(port_WB$copies.1mL != 0),]

## Included in results

## Copies
summary(unadj_time[which(unadj_time$Facility=="North"),"copies.1mL"])
summary(unadj_time[which(unadj_time$Facility=="South"),"copies.1mL"])
wilcox.test(unadj_time[which(unadj_time$Facility=="North"),"copies.1mL"], 
            unadj_time[which(unadj_time$Facility=="South"),"copies.1mL"], paired = TRUE, 
            alternative = "two.sided")

summary(port_EE$copies.1mL)
summary(port_WB$copies.1mL)
wilcox.test(port_EE$copies.1mL, port_WB$copies.1mL, paired = TRUE, 
            alternative = "two.sided")


## Cases
summary(unadj_time[which(unadj_time$Facility=="North"),"IncRate"]*10000)
summary(unadj_time[which(unadj_time$Facility=="South"),"IncRate"])*10000
wilcox.test(unadj_time[which(unadj_time$Facility=="North"),"IncRate"]*10000, 
            unadj_time[which(unadj_time$Facility=="South"),"IncRate"]*10000, paired = TRUE, 
            alternative = "two.sided")

summary(port_EE$IncRate*10000)
summary(port_WB$IncRate*10000)
wilcox.test(port_EE$IncRate*10000, port_WB$IncRate*10000, paired = TRUE, 
            alternative = "two.sided")

## Flow
summary(unadj_time[which(unadj_time$Facility=="North"),"FlowRate_MGD"])
summary(unadj_time[which(unadj_time$Facility=="South"),"FlowRate_MGD"])
wilcox.test(as.numeric(unadj_time[which(unadj_time$Facility=="North"),"FlowRate_MGD"]), 
            as.numeric(unadj_time[which(unadj_time$Facility=="South"),"FlowRate_MGD"]), paired = TRUE, 
            alternative = "two.sided")

summary(port_EE$FlowRate_MGD)
summary(port_WB$FlowRate_MGD)
wilcox.test(port_EE$FlowRate_MGD, port_WB$FlowRate_MGD, paired = TRUE, 
            alternative = "two.sided")


```

## Time lag - MA only
```{r}
lagtable<-data.frame("Beta"=NA,"R2"=NA,"RMSE"=NA)
##########################################################################################
## LINEAR
##########################################################################################
## MA - 4 day
summary(res<-lm(log(IncRate) ~ log(copies.1mL) + FlowRate_MGD + TAVG + Facility, data=adj_4day))
confint(res)
sqrt(mean(res$residuals^2))
lagtable["Linear 4 day",]<-c(paste(round(res$coefficients["log(copies.1mL)"],digits=2)," (",
                                   round(confint(res)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(res)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(summary(res)$adj.r.squared,digits=2),
                             round(sqrt(mean(res$residuals^2)),digits=2))
## MA - 5 day
summary(res<-lm(log(IncRate) ~ log(copies.1mL) + FlowRate_MGD + TAVG + Facility, data=adj_5day))
confint(res)
sqrt(mean(res$residuals^2))
lagtable["Linear 5 day",]<-c(paste(round(res$coefficients["log(copies.1mL)"],digits=2)," (",
                                   round(confint(res)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(res)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(summary(res)$adj.r.squared,digits=2),
                             round(sqrt(mean(res$residuals^2)),digits=2))

## MA - 6 day
summary(res<-lm(log(IncRate) ~ log(copies.1mL) + FlowRate_MGD + TAVG + Facility, data=adj_6day))
confint(res)
sqrt(mean(res$residuals^2))
lagtable["Linear 6 day",]<-c(paste(round(res$coefficients["log(copies.1mL)"],digits=2)," (",
                                   round(confint(res)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(res)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(summary(res)$adj.r.squared,digits=2),
                             round(sqrt(mean(res$residuals^2)),digits=2))

##########################################################################################
## GAM
##########################################################################################
## MA - 4 day
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr") + FlowRate_MGD + TAVG + Facility,
                 data=adj_4day))
sqrt(mean(gam$residuals^2))
lagtable["GAM 4 day",]<-c("insert p",
                          round(summary(gam)$r.sq,digits=2),
                          round(sqrt(mean(gam$residuals^2)),digits=2))


## MA - 5 day
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr") + FlowRate_MGD + TAVG + Facility,
                 data=adj_5day))
sqrt(mean(gam$residuals^2))
lagtable["GAM 5 day",]<-c("insert p",
                          round(summary(gam)$r.sq,digits=2),
                          round(sqrt(mean(gam$residuals^2)),digits=2))

## MA - 6 day
summary(gam<-gam(log(IncRate) ~ s(log(copies.1mL), bs="cr") + FlowRate_MGD + TAVG + Facility,
                 data=adj_6day))
sqrt(mean(gam$residuals^2))
lagtable["GAM 6 day",]<-c("insert p",
                          round(summary(gam)$r.sq,digits=2),
                          round(sqrt(mean(gam$residuals^2)),digits=2))


##########################################################################################
## POISSON
##########################################################################################
## MA - 4 day
summary(poisson <- glm(round(adj_4day$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, family="poisson", data=adj_4day))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
lagtable["Poisson 4 day",]<-c(paste(round(poisson$coefficients["log(copies.1mL)"],
                                          digits=2)," (",
                                   round(confint(poisson)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(poisson)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(PseudoR2(poisson, which = 'McFadden'),digits=2),
                             round(sqrt(mean(poisson$residuals^2)),digits=2))

## MA - 5 day
summary(poisson <- glm(round(adj_5day$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, family="poisson", data=adj_5day))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
lagtable["Poisson 5 day",]<-c(paste(round(poisson$coefficients["log(copies.1mL)"],
                                          digits=2)," (",
                                   round(confint(poisson)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(poisson)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(PseudoR2(poisson, which = 'McFadden'),digits=2),
                             round(sqrt(mean(poisson$residuals^2)),digits=2))

## MA - 6 day
summary(poisson <- glm(round(adj_6day$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, family="poisson", data=adj_6day))
confint(poisson)
PseudoR2(poisson, which = 'McFadden')
sqrt(mean(poisson$residuals^2))
lagtable["Poisson 6 day",]<-c(paste(round(poisson$coefficients["log(copies.1mL)"],
                                          digits=2)," (",
                                   round(confint(poisson)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(poisson)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(PseudoR2(poisson, which = 'McFadden'),digits=2),
                             round(sqrt(mean(poisson$residuals^2)),digits=2))

##########################################################################################
## NEG BINOMIAL
##########################################################################################
## Original code for reference:
# summary(negbin <- glm.nb(round(unadj_time$NewCases, digits=0) ~ log(copies.1mL) + 
#                            FlowRate_MGD + TAVG + Facility, data=unadj_time))

## MA - 4 day
summary(negbin <- glm.nb(round(adj_4day$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, data=adj_4day))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
lagtable["negbin 4 day",]<-c(paste(round(negbin$coefficients["log(copies.1mL)"],
                                          digits=2)," (",
                                   round(confint(negbin)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(negbin)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(PseudoR2(negbin, which = 'McFadden'),digits=2),
                             round(sqrt(mean(negbin$residuals^2)),digits=2))

## MA - 5 day
summary(negbin <- glm.nb(round(adj_5day$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, data=adj_5day))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
lagtable["negbin 5 day",]<-c(paste(round(negbin$coefficients["log(copies.1mL)"],
                                          digits=2)," (",
                                   round(confint(negbin)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(negbin)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(PseudoR2(negbin, which = 'McFadden'),digits=2),
                             round(sqrt(mean(negbin$residuals^2)),digits=2))

## MA - 6 day
summary(negbin <- glm.nb(round(adj_6day$NewCases, digits=0) ~ log(copies.1mL) + 
                         FlowRate_MGD + TAVG + Facility, data=adj_6day))
confint(negbin)
PseudoR2(negbin, which = 'McFadden')
sqrt(mean(negbin$residuals^2))
lagtable["negbin 6 day",]<-c(paste(round(negbin$coefficients["log(copies.1mL)"],
                                          digits=2)," (",
                                   round(confint(negbin)["log(copies.1mL)",1],digits=2),
                                   ", ",
                                   round(confint(negbin)["log(copies.1mL)",2],digits=2),")",
                                   sep=""),
                             round(PseudoR2(negbin, which = 'McFadden'),digits=2),
                             round(sqrt(mean(negbin$residuals^2)),digits=2))

lagtable
write.csv(lagtable,"LagTable.csv")

```